config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :gardens do
    resources :plants, only: :create
  end
  resources :plants, only: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/garden.rb
class Garden < ApplicationRecord
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: %i[ show edit update destroy ]

  # GET /gardens
  def index
    @gardens = Garden.all
  end

  # GET /gardens/1
  def show
  end

  # GET /gardens/new
  def new
    @garden = Garden.new
  end

  # GET /gardens/1/edit
  def edit
  end

  # POST /gardens
  def create
    @garden = Garden.new(garden_params)

    if @garden.save
      redirect_to @garden, notice: "Garden was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /gardens/1
  def update
    if @garden.update(garden_params)
      redirect_to @garden, notice: "Garden was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /gardens/1
  def destroy
    @garden.destroy
    redirect_to gardens_url, notice: "Garden was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_garden
      @garden = Garden.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def garden_params
      params.require(:garden).permit(:name, :banner_url)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def create
    @garden = Garden.find(params[:garden_id])
    @plant = Plant.new(plant_params)
    @plant.garden = @garden
    if @plant.save
      redirect_to garden_path(@garden)
    else
      @plants = @garden.plants
      render "gardens/show", status: :unprocessable_entity
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy
    redirect_to garden_path(@plant.garden), status: :see_other
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gardens/_form.html.erb
<%= simple_form_for(@garden) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :banner_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/gardens/_garden.html.erb
<div id="<%= dom_id garden %>">
  <p>
    <strong>Name:</strong>
    <%= garden.name %>
  </p>

  <p>
    <strong>Banner url:</strong>
    <%= garden.banner_url %>
  </p>

</div>

app/views/gardens/edit.html.erb
<h1>Editing garden</h1>

<%= render "form", garden: @garden %>

<br>

<div>
  <%= link_to "Show this garden", @garden %> |
  <%= link_to "Back to gardens", gardens_path %>
</div>

app/views/gardens/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Gardens</h1>

<div id="gardens">
  <% @gardens.each do |garden| %>
    <%= render garden %>
    <p>
      <%= link_to "Show this garden", garden %>
    </p>
  <% end %>
</div>

<%= link_to "New garden", new_garden_path %>

app/views/gardens/new.html.erb
<h1>New garden</h1>

<%= render "form", garden: @garden %>

<br>

<div>
  <%= link_to "Back to gardens", gardens_path %>
</div>

app/views/gardens/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= @garden.banner_url %>');">
  <div class="container">
    <h1><%= @garden.name %></h1>
  </div>
</div>

<div class="container">
  <div class="row mt-5">
    <% @garden.plants.each do |plant| %>
      <div class="col-4">
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= plant.image_url %>')">
          <%= plant.name %>
          <%= link_to "+", plant_path(plant), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "card-remove-link" %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row my-5 justify-content-center">
    <div class="col-4">
      <h4>Add a plant</h4>
      <%= simple_form_for [@garden, @plant] do |f| %>
        <%= f.input :name, placeholder: "Palm tree" %>
        <%= f.input :image_url, placeholder: "https://some_nice_image_found_on_google.jpg" %>
        <%= f.submit "Add", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyGarden</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>